// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List the signed-in user's events with basic details (name, date, venue, status).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db(ctx).from("events").select("id, name, event_date, venue, status, expected_guests, created_at").order("event_date", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data }
    };
  }
});

// src/lib/mcp/tools/list-guests.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_guests_default = defineTool2({
  name: "list_guests",
  title: "List guests for an event",
  description: "List guests for a specific event owned by the signed-in user.",
  inputSchema: {
    event_id: z2.string().uuid().describe("The event UUID."),
    limit: z2.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db2(ctx).from("guests").select("id, full_name, phone, category, status, checked_in, created_at").eq("event_id", event_id).order("created_at", { ascending: false }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { guests: data }
    };
  }
});

// src/lib/mcp/tools/list-pledges.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pledges_default = defineTool3({
  name: "list_pledges",
  title: "List pledges",
  description: "List pledges, optionally filtered by event_id, for the signed-in user.",
  inputSchema: {
    event_id: z3.string().uuid().optional().describe("Optional event UUID filter."),
    limit: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db3(ctx).from("pledges").select("id, event_id, pledger_name, pledger_phone, amount_pledged, amount_paid, status, due_date, created_at").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (event_id) q = q.eq("event_id", event_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { pledges: data }
    };
  }
});

// src/lib/mcp/tools/event-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var event_summary_default = defineTool4({
  name: "event_summary",
  title: "Event summary",
  description: "Return counts and totals for a specific event: guests, checked-in, pledges, and amounts pledged/paid.",
  inputSchema: { event_id: z4.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = db4(ctx);
    const [eventRes, guestsRes, pledgesRes] = await Promise.all([
      supabase.from("events").select("id, name, event_date, venue, status, expected_guests").eq("id", event_id).maybeSingle(),
      supabase.from("guests").select("id, checked_in").eq("event_id", event_id),
      supabase.from("pledges").select("amount_pledged, amount_paid, status").eq("event_id", event_id)
    ]);
    if (eventRes.error) return { content: [{ type: "text", text: eventRes.error.message }], isError: true };
    if (!eventRes.data) return { content: [{ type: "text", text: "Event not found" }], isError: true };
    const guests = guestsRes.data ?? [];
    const pledges = pledgesRes.data ?? [];
    const totalPledged = pledges.reduce((s, p) => s + Number(p.amount_pledged || 0), 0);
    const totalPaid = pledges.reduce((s, p) => s + Number(p.amount_paid || 0), 0);
    const summary = {
      event: eventRes.data,
      guests: { total: guests.length, checked_in: guests.filter((g) => g.checked_in).length },
      pledges: {
        total: pledges.length,
        total_pledged_tzs: totalPledged,
        total_paid_tzs: totalPaid,
        outstanding_tzs: Math.max(0, totalPledged - totalPaid)
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_invoices_default = defineTool5({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices for the signed-in user, optionally filtered by status.",
  inputSchema: {
    status: z5.string().optional().describe("Optional status filter (e.g. draft, sent, paid)."),
    limit: z5.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db5(ctx).from("invoices").select("id, invoice_number, client_name, total_amount, status, issue_date, due_date").order("issue_date", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { invoices: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "folppemingnczaohhngg";
var mcp_default = defineMcp({
  name: "smart-events-mcp",
  title: "Smart Events",
  version: "0.1.0",
  instructions: "Tools for the Smart Events Tanzania platform. Read the signed-in user's events, guests, pledges, invoices, and per-event summaries. All calls are scoped to the authenticated user via row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, list_guests_default, list_pledges_default, event_summary_default, list_invoices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
